--- # Testing the J2 Template Module
- hosts: web
  connection: ssh
  user: vagrant
  sudo: yes
  gather_facts: yes
  vars:
     userName: vagrant
     userPassword: vagrant
     connectionType: SFTP
  tasks:
    - name: Install the configuration file customized for the system
      template: src=test.conf.j2 dest=/home/vagrant/test.conf owner=vagrant group=vagrant mode=750
