---
# Upgrade VMs
- hosts: vms
  vars:
   var_remote_user: vagrant
   var_sudo: yes
  remote_user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  gather_facts: yes
  tasks:
  - name: update selected packages on Redhat Based System
    when: ansible_os_family == "RedHat"
    yum: name={{ item }} state=latest
    async: 40
    poll: 10
    with_items:
    - zip
    - unzip
    - wget
    - sysstat
    - ntp
    - telnet
  - name: update select packages on Debian Based System
    when: ansible_os_family == "Debian"
    apt:  name={{ item }} state=latest
    async: 40
    poll: 10
    with_items:
    - zip
    - unzip
    - wget
    - sysstat
    - ntp
    - telnet
