--- #MASTER PLAYBOOK FOR WEBSERVERS
- hosts: "{{ var_hosts }}"
#  user: "{{ var_remote_user }}"
#  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files: 
         - redhat_os_upgrade/vars/main.yml 
  pre_tasks:
  - name: Checking for current yum update before patching
    shell: 'yum check-update > /home/vagrant/yum_cu_pre.log  || test $? -eq 100'
  - name: Fetching The yum check-update before upgrade
    fetch: src=/home/vagrant/yum_cu_pre.log dest=/home/vagrant/logs/yum_cu_pre.log.{{ ansible_hostname }} flat=yes chmod=750
  roles:
    - redhat_os_upgrade
