- name: Restart HTTPD
  service: name=httpd state=restarted
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
- name: Restart APACHE2
  service: name=apache2 state=restarted
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
