- name: Install Apache Web Server On ReHat Based System
  yum: pkg={{ redhat_apache }} state=latest
  when: "ansible_os_family == 'RedHat'"
  ignore_errors: yes
#  notify: Restart HTTPD
#- name: Wait for Service to start listening on Port 80
#  wait_for:
#     port: 80
- name: Verify Service Status
  shell: service httpd status
  register: result
  until: result.stdout.find("running") != -1
  retries: 5
  delay: 5
- debug: var=result
- name: Add a List of Software
  yum: pkg={{ item }} state=latest
  with_items:
  - telnet
  - lynx
  tags: install_list
- name: Install Apache Web Server On Debian Based System
  apt: pkg={{ debian_apache }} state=latest
  when: "ansible_os_family == 'Debian'"
  ignore_errors: yes
  notify: Restart APACHE2
